### ISSUE TITLE
Example Wrong

### ISSUE THREAD

**Issue by jayonsoftware** [daveaglick/Scripty#11]
int propertyName = "Bar";
Output.WriteLine($@"
class Foo 
{{ 
    int {propertyName} => 42; 
}}");

It should be 

string propertyName = "Bar";

Also any plans on adding more samples ?

**Comment by daveaglick** [comment]
Good catch, thanks! Can't very well be assigning a `string` to an `int` variable. I'll correct it on the next commit.

> any plans on adding more samples

Yep, have some more low-level stuff to clean up first and then planning to work on samples and additional documentation, including some example projects that actually execute. I'll probably end up creating a dedicated web site at some point too.
