### ISSUE TITLE
Dead Project ?

### ISSUE THREAD

**Issue by LucaGabi** [daveaglick/Scripty#133]
Hi,

Has this project died ?

I noticed the hint in the repo but .. .Net Core seems ready now .. or not ?

**Comment by daveaglick** [comment]
Yeah, .NET Core is certainly ready. I just haven't had the time lately to dive back in. If/when I do, the underlying architecture will likely change quite a bit. At the moment though, I'm backed up into late this year with other open source initiatives.

TL;DR: I'd love to revisit this project at some point but have no immediate plans to do so.
