### ISSUE TITLE
Is this project dead?  What do we use to generate code with .NET Core 3.1?

### ISSUE THREAD

**Issue by dfarrNTST** [daveaglick/Scripty#136]
This repo says its not dead, but its been years since anything has appeared here.  Is this project officially dead and we should look for a better future alternative?  Roslyn CodeAnalysis by itself seems very limiting in control of the structure.  Is there a .NET Core 3.1 compatible T4 library somewhere?

**Comment by daveaglick** [comment]
Scripty is in a funny spot. I would love to get back to it, and still think I might someday, but almost all of my OSS time recently is being invested in Statiq (https://github.com/statiqdev) and Discover .NET (https://discoverdot.net/). Given the scale of both of those projects it’s doubtful I’ll have any serious time to devote to Scripty for a while.

One possible alternative is https://github.com/AArnott/CodeGeneration.Roslyn. I also saw some noise recently that the Roslyn team is (finally!) starting to investigate adding code generation capabilities out of the box.
