### ISSUE TITLE
Fluent indention methods

### ISSUE THREAD

**Issue by Herdo** [daveaglick/Scripty#15]
A fluent indention API should be introduced.
### Background:

If the scripts reach a deeper nesting level, the amount of additional whitespaces in the output will be overwhelming. Most lines of the scripts will be way longer than they should be.
#### Example:

This one might be readable, as long as you can write a single interpolated string...

``` c#
Output.WriteLine(@"MyNamespace
{
    public class MyClass : IMyInterface
    {
        public string MyStringProperty { get; set; }
    }
}");
```

... but the more complex the script gets...

``` c#
Output.WriteLine(@"MyNamespace
{");
foreach(var enumType in enumTypesFromDatabase)
{
    // One shouldn't need to write the beginning whitespaces every time:
    Output.Write($"    public enum {enumType.ClassName}");
    if (enumType.BaseType != typeof(int))
    {
        Output.Write($" : {enumType.BaseType.Name}");
    }
    Output.WriteLine("");
    // As well as those whitespaces:
    Output.WriteLine("    {");
    foreach(var enumMember in enumType.Members)
    {
        // Already now, the number of additional whitespaces is...well...
        Output.WriteLine($"        {enumMember.ValueName} = {enumMember.Value},");
    }
    // And those:
    Output.WriteLine("    }");
}
Output.WriteLine("}");
```
### Fluent indention API

The fluent indention API would a very easy thing to read:

``` c#
Output.WriteLine(@"MyNamespace
{");
using (Output.Indent())
{
    // Everything inside this block would be indented
    Output.WriteLine(@"public class MyClass
{");
    using (Output.Indent())
    {
        // Everything inside this block would be indented by another level
    }
Output.WriteLine("}");
}
Output.WriteLine("}");
```

Additionally, the indention should be configurable:
`Output.IndentionCharacter` - will get or set the indention character (default whitespace)
`Output.IndentionRepeat` - will get or set the amount of times, the `IndentionCharacer` will be repeated for each `Indent()` (default 4)

**Comment by Herdo** [comment]
Methods created in #12 should also provide the fluent indention API:

``` c#
using (Output.WriteNamespace("MyNamespace").IndentContent())
{
    Output.WriteLine("// Content goes here");
}
```

The code above would result in this output:

``` c#
MyNamespace
{
    // Content goes here
}
```

**Comment by Herdo** [comment]
@daveaglick Hey Dave, I'd like to push some changes for this issue.
It's the partial code that needs to be consumed in the classes deriving from OutputFile.
Kindly asking for permissions.

**Comment by daveaglick** [comment]
Go ahead and submit a PR so we can take a look at it. I'm still not totally comfortable with the proposed API yet, so I'm very curious to see what you've come up with.

One of the design goals was to keep the plumbing and extra global code as light as possible so that it's easier to host Scripty scripts outside the "official" Scripty runners. Depending on how heavy this feature gets, perhaps it'll be appropriate for a separate Scripty.Extensions package or something that can contain additional global objects, methods, extensions, etc.

**Comment by Herdo** [comment]
An additional namespace to separate base functionality and "extensions" might be a good idea!

**Comment by daveaglick** [comment]
This functionality has been added to the develop branch (with a somewhat different API than discussed above after lots of thought).

**Comment by DamianReeves** [comment]
Any plans on releasing this to the NuGet feed? The current package doesn't include this functionality.

**Comment by daveaglick** [comment]
@DamianReeves Yeah, "soon" :) - at this point there's some nagging issues I'm having on a couple test platforms. That's been keeping me from publishing for a few weeks. Hoping to get those worked out and get a new release out the door before too long.
