### ISSUE TITLE
Add Support To Change The File Extension

### ISSUE THREAD

**Issue by TylerBrinkley** [daveaglick/Scripty#19]
It'd be great if you could add the ability to change Output's file extension without having to manually specify the entire filename. My use case for this is that I currently use T4 to generate json configuration settings and as such would like the output to have a .json extension.

**Comment by daveaglick** [comment]
Any suggestions what this API should look like? Is something like this what you had in mind?

```
Output.SetExtension(".json");
Output.WriteLine(...);
```

In the interim, this should do the trick (though it's obviously not as elegant):

```
string outputPath = Path.ChangeExtension(ScriptFilePath, ".json");
Output[outputPath].WriteLine(...);
```

**Comment by TylerBrinkley** [comment]
Thanks, that API looks good to me. I'll use your solution for now.

**Comment by Herdo** [comment]
`Output.SetExtension(string extension)` should allow the following:
- ".json" as normal file extension
- "json" without the dot
- ".json.partial" (e.g. two file extensions) 
- "json.partial" (same as above)

**Comment by daveaglick** [comment]
This is now implemented in the develop branch and will go out with the next release.
