### ISSUE TITLE
Add Empty Scripty File Item Template

### ISSUE THREAD

**Issue by TylerBrinkley** [daveaglick/Scripty#20]
In Visual Studio, to prevent needing to manually specify the file extension as .csx and setting the Custom Tool to ScriptyGenerator an Empty Scripty File Item Template should be included in the Visual Studio Extension.

By the way, I'm loving Scripty so much vs T4. Now, if only we could get Intellisense on assemblies loaded with the #r directive in Visual Studio this would be the ultimate solution.

**Comment by daveaglick** [comment]
Glad it's working well for you! I suspect that the VS team is going to continue improving Intellisense support for Roslyn scripts. In fact, that's one of the main reasons the default Scripty extension is `.csx`, so we can get all the Roslyn script editing functionality for free.

As far as an item template, that's being tracked over in #14. I don't know that it'll make it into the very next release, but I'll be adding it relatively soon.

**Comment by TylerBrinkley** [comment]
Sorry, I didn't see that other issue. Thanks.

**Comment by daveaglick** [comment]
Np :smile:
