### ISSUE TITLE
How to /(or can I) import an third-party assembly in the script? 

### ISSUE THREAD

**Issue by ghost** [daveaglick/Scripty#23]
as titled, thanks!

**Comment by TylerBrinkley** [comment]
You use the #r preprocessor directive at the top of the script like so.

```
#r "..\Libs\Newtonsoft.Json.dll"
```

**Comment by ghost** [comment]
Thanks! great job! trying to replace t4 in my project.

**Comment by daveaglick** [comment]
@szqianx Cool! Just file an issue if you have any other questions.
