### ISSUE TITLE
Discussion: Generic Scripty.Extension namespace & classes

### ISSUE THREAD

**Issue by Herdo** [daveaglick/Scripty#27]
This discussion is based on this comment:
https://github.com/daveaglick/Scripty/issues/15#issuecomment-227525617

I like the idea of having a pluggable extension API for the `OutputFile`.
Given the following interfaces:

``` c#
public interface IExtension
{
    // Might provide basics for further extensions later on
}

public interface IOutputFileExtension : IExtension
{
    string ModifyOutput(string input);
}
```

The `OutputFile` class could provide this functionality:

``` c#
public OutputFile Use<TExtension>() where TExtension : IOutputFileExtension
{
    // Resolve TExtension and add to internal list
}
```

The `Write` methods could then use the "registered" extensions, chained one after another,
before writing the output to the stream writer.
### Example:

``` c#
OutputFile.Use<IIndentionExtension>()
          .Use<IPascalCasingExtension>() // Just an example!
          ...
```

Calling `OutputFile.WriteLine("myText")` would invoke the `IIndentionExtension`, then the `IPascalCasingExtension`:
1. `"myText"`
2. `"    myText"`
3. `"    MyText"`
4. and so on...
### Configuring the extensions

The instance of an "activated" extension can be retrieved via a `Get` method:

``` c#
public TExtension Get<TExtension>()
{
    // Get activated extension in OutputFile instance
}
```

The instance retrieved can then be used to configure the extension.

**Comment by daveaglick** [comment]
From a purely technical perspective, I think the design is neat. I have reservations about it in this context though. My first gut reaction is that it seems a bit complicated for what's supposed to be a simple and lightweight way to stream/output text to disk. And if the indentation support gets implemented directly (which I think looks likely), I also have a hard time coming up with good use cases for additional extensions that couldn't be covered by plain old extension methods.

I'll think on it some more over the next couple days, but I'm leaning towards deferring this idea for now...

**Comment by daveaglick** [comment]
Thought about this _a lot_ recently. I'm going to go ahead and close this issue. I really appreciate that you've given this so much thought and are interested in improving the library. However, I'm going to focus efforts in the foreseeable future on smaller, more focused enhancements and the core functionality.

Any preprocessing work that needs to be done on output content (such as the casing example above) can be done with a custom `TextWriter` that wraps the Scripty `OutputFile` (much the same way Scripty itself wraps a `TextWriter`). These could even be nested to provide multiple output preprocessors.
