### ISSUE TITLE
Diificulty calling SemanticModel.GetDeclaredType etc

### ISSUE THREAD

**Issue by salmelo** [daveaglick/Scripty#40]
This simple script:

``` c#
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis;
using System.Linq;

var doc = Project.Analysis.Documents.First();
var model = doc.GetSemanticModelAsync().Result;
var tree = doc.GetSyntaxTreeAsync().Result;

var typeDeclarations = tree.GetRoot().DescendantNodes().OfType<BaseTypeDeclarationSyntax>();

Output.WriteLine($"//{doc.Name}");
foreach (var type in typeDeclarations)
{
    var symbol = model.GetDeclaredSymbol(type);
    Output.WriteLine($"// {symbol.Name}");
}
```

Fails with the error: "Custom tool error: Argument 2: cannot convert from 'Microsoft.CodeAnalysis.CSharp.Syntax.BaseTypeDeclarationSyntax' to 'Microsoft.CodeAnalysis.SyntaxNode'"

Which is weird since BaseTypeDeclarationSyntax eventually inherits from SyntaxNode, so it should be able to convert just fine.
`type as SyntaxNode` and `(SyntaxNode)type` also fail, with similar errors.

Running the entire IEnumerable through `.Cast<SyntaxNode>()` works just fine however. Still, it's an annoying workaround since your various syntax elements won't always be in an IEnumerable and even when they are you may still want to get at the data in the more specific classes.

No clue if this is a Scripty issue or a Roslyn issue, but I thought it was worth mentioning. I'm wondering if it has something to do with the script not having a reference to Microsoft.CodeAnalysis.CSsarp.dll, but I don't know where it might be hiding I can't test that idea.

**Comment by daveaglick** [comment]
@salmelo This is a pretty old issue, so no idea if you're even still using Scripty. If you are, can you try testing it with the latest version? I've updated all the Roslyn libraries and it might help resolve this issue.

**Comment by salmelo** [comment]
Looks like it's working now, at least in the quick test I threw together.

**Comment by daveaglick** [comment]
Awesome! Thanks for testing it out.
