### ISSUE TITLE
Add Option To Prevent Generating Log

### ISSUE THREAD

**Issue by TylerBrinkley** [daveaglick/Scripty#53]
Could you add an option in Scripty on ScriptContext to prevent generating the log file? I'd rather not have them added to the solution and source control.

**Comment by strich** [comment]
This is also a top request for us - It is a real pain in our project source control.

**Comment by Herdo** [comment]
Wouldn't it be a better option to output the log to the underlying command line?
See: [https://msdn.microsoft.com/en-us/library/ms221833.aspx](https://msdn.microsoft.com/en-us/library/ms221833.aspx)

Use case "**Debugging**":
The log output should be written into the Visual Studio "Build Output" window.

Use case "**Build server**":
The log output should be written into the appropriate build output log.

Preventing the log from being written would make it hard for new developers to find errors, if they are not logged.

**Comment by daveaglick** [comment]
I think the key here is to make logging a bit more extensible. Ideally it should be up to the user whether log output gets combined with MS Build output, sent to the console, written to a file, etc. Reasonable defaults for the different execution environments should be set, but overrides should be available in all cases.

**Comment by Herdo** [comment]
@daveaglick AFAIK, the current `Log` is a derived member of a base class.
Therefore, the whole logging mechanism would require a new implementation, right?

**Comment by daveaglick** [comment]
@Herdo Yep, it was a very quick and dirty logging implementation to get out the door. I had always intended to rip it out and replace with something else, probably based on `TraceSource`, `TraceListener`, etc.
