### ISSUE TITLE
VS 2015 Extension fails to run

### ISSUE THREAD

**Issue by strich** [daveaglick/Scripty#55]
Installed the extension in the latest version of VS 2015 update 3. Created a blank C# console project, made a file called `TestScriptGen.csx` and pasted the following code in it:

```
foreach (Document document in Project.Documents)
{
    Output.WriteLine($"// {document.FilePath}");
}
```

Added the Custom Tool `ScriptyGenerator` and attempted to run it - I get an error:

"The custom tool 'ScriptyGenerator' failed."

:(

**Comment by daveaglick** [comment]
Was this a .NET Framework or a .NET Core console application? I'd like to try and reproduce as closely as possible.

**Comment by strich** [comment]
.NET Framework. I was testing this on a normal .NET 4.6.1 project, however my ultimate intention is to use it on a Unity3D project, which generates .NET 3.x VS projects.

**Comment by daveaglick** [comment]
Looks like you just need to modify the script a bit. I got the following errors (you can see them by hovering over the script file, which should have a red underline after an unsuccessful generation):

![2016-09-27_14h24_31](https://cloud.githubusercontent.com/assets/1020407/18886606/92d77752-84be-11e6-8ead-9d6d7bb32e86.png)

The following modifications worked:

```
using Microsoft.CodeAnalysis;

foreach (Document document in Project.Analysis.Documents)
{
    Output.WriteLine($"// {document.FilePath}");
}
```

Notice I am including the `Microsoft.CodeAnalysis` namespace to bring the `Document` class into scope. I'm also accessing the Roslyn `Documents` property as a member of the `Analysis` property from the `Project` global property.

**Comment by strich** [comment]
Great this worked. Two things however:
1. You should update your README with that code snippet.
2. At least in my VS I do not ever see any red lines indicating there are errors to be viewed. I did however see the errors when I manually looked in the Errors window tab.

**Comment by daveaglick** [comment]
Great, glad you've got it working! I have ReSharper installed so the red lines on the file might be coming from that instead of VS.
