### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [daveaglick/Scripty#56]
i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#152

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by gep13** [comment]
@daveaglick just wanted to touch base to see if you had thought about doing this. Thanks!

**Comment by daveaglick** [comment]
Yeah, fully intend to. Just keeps dropping off my radar.

**Comment by gep13** [comment]
Ping 😄

**Comment by daveaglick** [comment]
https://github.com/cake-build/website/pull/348

![its-happening](https://cloud.githubusercontent.com/assets/1020407/25405261/c3134aba-29d0-11e7-93f5-88904ab9aa9d.gif)

**Comment by gep13** [comment]
WOOT!
