### ISSUE TITLE
Change ScriptFiles item group name to ScriptyFiles

### ISSUE THREAD

**Issue by daveaglick** [daveaglick/Scripty#6]
This will avoid collisions given the name is overly generic

**Comment by wgebczyk** [comment]
**usually** Item names are singular. You might consider to use "ScriptyFile"

**Comment by daveaglick** [comment]
@wgebczyk In this case, it's the name of an `ItemGroup` element in the MSBuild target that gets passed into a property in the MSBuild task. Since the property is intended to take a collection, it probably makes sense to pluralize the element name too so they match.

**Comment by wgebczyk** [comment]
Hmm... Like multiple "Reference", "ProjectReference", "Compile", "Page", "Resource", "Content", etc...
- your tool, your naming :)

**Comment by daveaglick** [comment]
@wgebczyk Ah, see your point! Indeed, all those elements can take single or multiple includes... No naming issue is too small to deliberate :smile: - I'll give this one a little thought.

**Comment by crash-dive** [comment]
@daveaglick The docs on the main page were not updated to reflect this change. It still reads 
``` xml
<ScriptFiles Include="codegen.csx" /> 
````
which caused me some confusion.

Thanks for the tool, it is a lot easier than T4 has been.
