### ISSUE TITLE
Compatibility with VS 2017

### ISSUE THREAD

**Issue by djanosik** [daveaglick/Scripty#62]
It looks like neither the VS extension nor the MsBuild package works in VS 2017. It causes as a lot of troubles. Please, can you check?

**Comment by TorreyGarland** [comment]
Got it to work in vs 2017 class library by setting the target framework to 4.6.

**Comment by daveaglick** [comment]
Excellent, thanks for the tip @TorreyGarland.

I've been crashing on a different OSS project for the last several months, but I'm hoping to get back to Scripty and clear some of the backlog soon.

**Comment by Guy--L** [comment]
In VS 2017 RC4, I did start with target framework as 4.6 and don't know enough msbuild to work around this:

1>C:\Users\guy\.nuget\packages\scripty.msbuild\0.6.0\build\Scripty.MsBuild.targets(27,5): error : Microsoft.Build.Exceptions.InvalidProjectFileException: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

Note also this answer:  http://stackoverflow.com/a/41870718/775729

**Comment by daveaglick** [comment]
VS 2017 support should be available in the just released 0.7.0

**Comment by Patrickkk** [comment]
When adding "ScriptyGenerator"as custom tool i get an error "Custom tool       One or more values are invalid. An Internal error occured. Having this issue for a new solution with a single .net core class librairy and the VS2017 extension installed. Might be related to .net core support... (#50 )

As a workaround for now i simply use the scripty CLI and it works fine.
