### ISSUE TITLE
Please add a contribution quick start

### ISSUE THREAD

**Issue by StingyJack** [daveaglick/Scripty#64]
I'm just looking for a "here's how to get started" guide, because I am dumb and F5 isnt working no matter how hard I press the key.

**Comment by daveaglick** [comment]
Will do - not sure when I'll get the time to write it up, but this is a great idea.

**Comment by StingyJack** [comment]
I figured out what was not working for me - VS install path is different from the project debug tab properties.

**Comment by daveaglick** [comment]
Thanks for taking the initiative on this - I'll go ahead and close out this issue since you've addressed it in your PR.
