### ISSUE TITLE
Create Cake addin

### ISSUE THREAD

**Issue by daveaglick** [daveaglick/Scripty#7]

**Comment by agc93** [comment]
Has this been started? I was thinking of starting one, but don't want to duplicate any effort..

**Comment by daveaglick** [comment]
@agc93 Haven't started it yet. Got more than enough to work on in the core, so it's yours if you want it! Note that I'll start #5 soon which will change the CLI a little by not requiring all the individual scripts to be specified (just the project).

**Comment by agc93** [comment]
Hmm, I might shelve this until #5 hits, then revisit. 

What do you think is the best approach? Building a `Tool<T>`-based CLI wrapper is obviously much simpler and makes the syntax easier, but it seems like doing a proper addin against `Scripty.Core` would be the _"better"_ approach, and lines up closer with what you have with `.MsBuild`, `.CustomTool` etc. Thoughts?
