### ISSUE TITLE
Attempt to move off of separate process

### ISSUE THREAD

**Issue by daveaglick** [daveaglick/Scripty#71]
Right now we have to launch MSBuild in a separate process since it can't run recursively. There might be a way around this as explained at https://github.com/dotnet/roslyn/issues/14206#issuecomment-254271050. Investigate if this will work and move to that approach if feasible.

**Comment by TylerBrinkley** [comment]
Currently, after running the Scripty custom tool I'm not able to rebuild the solution as Scripty holds onto the references to the .dll files it loads in the csx. I must therefore close Visual Studio and reopen it in order to rebuild the solution. Would what you're proposing fix this?

**Comment by daveaglick** [comment]
@TylerBrinkley Not sure without knowing the underlying reason why it's grabbing locks on the assemblies. I don't think this would help though.

Can you open a new issue regarding the locks? It clearly shouldn't be grabbing them - there might be something with regards to the custom tool life cycle and disposing the Roslyn compilation that I've overlooked.

**Comment by TylerBrinkley** [comment]
Thanks, I've added it as #72.

**Comment by per-samuelsson** [comment]
> There might be a way around this as explained at dotnet/roslyn#14206 (comment). Investigate if this will work and move to that approach if feasible.

Just be aware you are then [stuck on Windows]( https://github.com/dotnet/roslyn/issues/14206#issuecomment-278414045). Not sure about your x-plat strategy, but thought I'd just give you a hint of it anyway.

**Comment by daveaglick** [comment]
@per-samuelsson Thanks - that probably is a deal-breaker as I'd like to (eventually) move to Core.

There's also other problems with the approach like having to parse out all the arguments. After looking at this for a while yesterday, I'm going to stick with the process forking for now.

**Comment by per-samuelsson** [comment]
> @per-samuelsson Thanks - that probably is a deal-breaker as I'd like to (eventually) move to Core.

Sure thing. At the same time, I realized using `MsBuildWorkspace` probably fall under the same category, i.e. being Windows-specific too.

**Comment by StingyJack** [comment]
The custom tool may still need the separate process if script debugging is still in the plans.

**Comment by daveaglick** [comment]
Yeah, at this point what we have (mostly) works okay so I'm going to table moving away from the process fork for now. I think we're probably stuck on Windows one way or the other right now as long as we want to continue exposing the Roslyn workspace API.

I'm still holding out hope that long-term the new cross platform MSBuild library will offer something akin to the old DTE model from Visual Studio and we can totally do away with the whole Roslyn/MSBuild abstraction being used right now. It's a pain.

> if script debugging is still in the plans

Would love to get there, but as you may have noticed this isn't my primary project and I haven't been able to give it the attention it probably deserves. I've got no idea what the time line for that looks like.
