### ISSUE TITLE
Scripty custom tool holds onto dll file locks

### ISSUE THREAD

**Issue by TylerBrinkley** [daveaglick/Scripty#72]
Currently, after running the Scripty custom tool I'm not able to rebuild the solution as Scripty holds onto the references to the .dll files it loads in the csx. I must therefore close Visual Studio and reopen it in order to rebuild the solution.

**Comment by daveaglick** [comment]
How are you loading the assemblies in your script? I'm assuming with the `#r` directive but want to be sure.

**Comment by TylerBrinkley** [comment]
Correct, I'm loading it with the `#r` directive.

**Comment by TylerBrinkley** [comment]
When trying to build I get the following VS error.

```
Unable to copy file "C:\TFS\SB\Dev\Stifel.Bank.Encompass.SmartClient\Stifel.Bank\bin\Stifel.Bank.dll" to "bin\Stifel.Bank.dll". The process cannot access the file 'bin\Stifel.Bank.dll' because it is being used by another process.
```

**Comment by daveaglick** [comment]
Is this assembly also referenced by your containing project (or is it actually *the* containing project)?

**Comment by TylerBrinkley** [comment]
The assembly referenced is located in a separate project.

I've attached a minimal reproduction solution.

[ScriptyBug.zip](https://github.com/daveaglick/Scripty/files/761791/ScriptyBug.zip)

**Comment by TylerBrinkley** [comment]
Just build the solution, run the Content.csx script, then try building the solution again.

**Comment by StingyJack** [comment]
Was this with 0.5.0 or 0.6.0?

**Comment by TylerBrinkley** [comment]
This was with 0.5.0 but I don't think it was fixed for 0.6.0.

**Comment by StingyJack** [comment]
I see it in 0.6.0 also, i think it's VS that's holding the lock.  Running the script with the target project unloaded still causes the error until VS is restarted. Killing MSBuild or the VBCSCompiler doesn't release it. 

Did you try with scripty.exe to see if it locks the file?

**Comment by StingyJack** [comment]
I ran this through the changes I have for PR #75 and its not locking the file. I don't see anything obvious that would cause the reference locking though.

**Comment by daveaglick** [comment]
Now that 0.7.0 is (finally) released, I'll take a look at #75 and we can see if it resolves this issue.

**Comment by daveaglick** [comment]
@TylerBrinkley I know you're currently blocked by #84, and I'm hoping to get an update out for that today. Once it's out can you see if it also resolved this file locking issue? I addition to all the updates to Roslyn, we're also using a new version of the VS extensibility libraries. Perhaps those are better about releasing locks...

**Comment by TylerBrinkley** [comment]
This is still an issue with 0.7.0 of the custom tool which still works with .NET Framework projects. #84 only relates to the Scripty.MSBuild NuGet package.

**Comment by daveaglick** [comment]
Okay, thanks - 0.7.0 has the new VSIX stuff so that's a no-go for this issue then.

**Comment by ghost** [comment]
Is it possible this is another symptom of the same problem that's causing #52 ?
