### ISSUE TITLE
Compilation errors when using Custom Build Tool, but not from the command line

### ISSUE THREAD

**Issue by OliverHallam** [daveaglick/Scripty#79]
I'm trying to setup Scripty to generate some types in our project using Roslyn.

Here's a fairly minimal repro:

```c#
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Formatting;

var compilationUnit = SyntaxFactory.CompilationUnit();
var workspace = Project.Analysis.Solution.Workspace;
var formattedNode = Formatter.Format(compilationUnit, workspace);
formattedNode.WriteTo(Output);
```

When I run this from the command line, it runs without errors (generating an empty file), but invoking the custom tool from Visual Studio presents me with the following error:

Custom tool error: Argument 1: cannot convert from 'Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax' to 'Microsoft.CodeAnalysis.SyntaxNode'	

Do you have any ideas how I can fix this?

**Comment by daveaglick** [comment]
Suspect this may be a resolution problem between the version of Roslyn Scripty is using and the version that's loaded into memory by MSBuild. The current release of Scripty is a bit behind. I've already updated everything for the new version of Roslyn, C# 7, Visual Studio 2017, etc. in the develop branch. I'm just waiting on MS to fix a bug with VSIX publishing in VS 2017 before I can release everything.

Keep an eye out. With the amount of updates to dependencies, hopefully the new version will resolve your issue once it's released. I'll check back in then and see how you're doing.

**Comment by OliverHallam** [comment]
I think I've made some progress with this.

I've not referenced either of the Roslyn dlls explicitly, and it looks like it's implicitly pulled in 2.0.0 of Microsoft.CodeAnalysis.CSharp and 1.3.1 of Microsoft.CodeAnalysis.Workspaces and Microsoft.CodeAnalysis 1.3.1 which is what has caused the type conflict.

Adding a reference to Microsoft.CodeAnalysis.CSharp.dll v 1.3.1 makes the problem go away in visual studio:

```c#
#r "..\..\..\bin\Microsoft.CodeAnalysis.CSharp.dll"
```

This unfortunately means it no longer works from the command line tool, but is good enough for us for now.

**Comment by daveaglick** [comment]
:+1: Great! Go ahead and leave this issue open so we can circle back and see if the new release resolves the problem entirely.

**Comment by daveaglick** [comment]
I just released a new version that links against Roslyn 2.0.0. When you get a chance go ahead and give it a try to see if it resolves this one.

**Comment by daveaglick** [comment]
Going to close this issue - please open a new one if it looks like this remains unresolved or you hit the problem again.

**Comment by OliverHallam** [comment]
Thanks for fixing this.  I've been pulled off onto other things recently but I'm hoping I'll get a chance to look at this again soon.  I'm looking forward to reverting a lot of my workarounds!
