### ISSUE TITLE
Error when invoking msbuild outside of a solution

### ISSUE THREAD

**Issue by OliverHallam** [daveaglick/Scripty#81]
The MSBuild targets file passes the `$(SolutionPath)` property to the build task, which in turn passes this to the `--solution` flag for the command line tool.

This works correctly when building a solution, but if you invoke MSBuild directly on a .csproj, it seems that is sets `SolutionPath` to `*Undefined*` which causes an error:

    System.InvalidOperationException: Invalid solution file path: 'C:\projects\xxx\*Undefined*'

We have worked around this by adding the following to our scripty.targets file:

```xml
  <PropertyGroup>
    <_ScriptySolutionPath Condition="'$(SolutionPath)' != '*Undefined*'">$(SolutionPath)</_ScriptySolutionPath>
  </PropertyGroup>
```

and using `$(_ScriptySolutionPath)` in place of `$(SolutionPath)`.

**Comment by daveaglick** [comment]
Thanks for the detailed report! I ended up resolving by checking for `*Undefined*` within the task code and then not setting the CLI argument if it's in there.
