### ISSUE TITLE
Source file specified multiple times CSC Warning with Scripty.MSBuild

### ISSUE THREAD

**Issue by TylerBrinkley** [daveaglick/Scripty#83]
I've written a simple script to auto-increment the assembly file version of my AssemblyInfo.cs file upon build using the Scripty.MSBuild NuGet package. This is working well but I do get the following warning that I was hoping to clear up.

```
CSC : warning CS2002: Source file 'Properties\AssemblyInfo.cs' specified multiple times
```

I've verified in my csproj that the AssemblyInfo.cs is only listed once. Below is my script.

```c#
var text = System.IO.File.ReadAllText(ScriptFilePath.Substring(0, ScriptFilePath.Length - 1));
var assemblyFileVersionStr = @"AssemblyFileVersion(""";
var index = text.IndexOf(assemblyFileVersionStr) + assemblyFileVersionStr.Length;
var endIndex = text.IndexOf('"', index);
var version = System.Version.Parse(text.Substring(index, endIndex - index));
Output.Write(text.Substring(0, index)).Write($"{version.Major}.{version.Minor}.{version.Build}.{version.Revision + 1}").Write(text.Substring(endIndex));
```

**Comment by daveaglick** [comment]
Do you have both the MSBuild task and the VS extension installed? If so, this is probably the same as #34.

**Comment by TylerBrinkley** [comment]
Yeah, I think you're right. This is a dupe.

**Comment by daveaglick** [comment]
FWIW, that one is high on my radar. I'll probably tackle it next once all the post-upgrade problems are resolved.

**Comment by TylerBrinkley** [comment]
It's really not a big issue for me as it's just a warning but eventually it'd be nice if it didn't show up.
