### ISSUE TITLE
Please explain the "CustomTool" for me please

### ISSUE THREAD

**Issue by finite8** [daveaglick/Scripty#85]
I'm seeing a lot of people saying "They added the custom tool for ScriptyGenerator" but I';m not seeing any examples of what was actually done in order to get scripty support working in VisualStudio. I believe i have to change my CSProj file somehow, but i cannot find any clear instructions on what i should be doing to get it working.

**Comment by finite8** [comment]
Just in case anyone else has the same problem:
![image](https://cloud.githubusercontent.com/assets/7815382/24527571/7f09e2a2-15ee-11e7-9ab1-4b24b434f91d.png)

**Comment by daveaglick** [comment]
Glad you were able to figure this out. The documentation for this setting is here (see second paragraph): https://github.com/daveaglick/Scripty#scriptycustomtool. It could probably be clearer - perhaps I'll add your screen shot. And as for that, thanks for following up with it to help anyone else who may stumble here.

**Comment by finite8** [comment]
Yeah, totally get that. Its sucks documenting your own stuff. You don't know what YOU know that others don't.

**Comment by JCKodel** [comment]
Extra tip: the "Properties" toolbox window is contextual. If you, as me, hide it, just select the .csx file you want to change and press [F4] (or whatever keybinding you're using for View.PropertiesWindow):

![image](https://user-images.githubusercontent.com/379339/28591490-52367708-715c-11e7-8835-b3d20e89b5b4.png)
