### ISSUE TITLE
Assembly resolution issue

### ISSUE THREAD

**Issue by finite8** [daveaglick/Scripty#86]
I have just solved this issue for a T4 template but i was getting the same problem with the Scripty CSX file i was trying to put together to replace said T4 script, so I'll put this here to help out.

I was getting all sorts of unusual assembly resolution failures. I was putting together a script that would load my Domain objects from an assembly and generate a cs file for my project (codegen) based on it. The problem was that these objects used a shared interface that had their implementation from another library of mine and i was encountering all sorts of vague issues. Best i got was "Could not load type", and the Fusion log would just tell me that the dll file could not be found, even though i gave it an explicit file reference.

As it turns out, the problem was far different to what i expected. Visual Studio had for some reason cached some old versions of my dlls in its own folder (C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE) and no matter what "#r" tags i used, it would keep using the ones from this folder instead which caused problems with my type loading. Removing all of the issue assemblies from this path stopped the issue and it builds fine now.

Hope that helps.

**Comment by daveaglick** [comment]
I don't think there's any way Scripty can clear that stuff out automatically, but thanks a lot for the detailed explanation of the problem! Hopefully that will be helpful to next person who has a similar issue and stumbles on this one with a resolution.
