### ISSUE TITLE
Illigal Charater in file path

### ISSUE THREAD

**Issue by biqas** [daveaglick/Scripty#87]
Hi,

if your solution reside in a folder with spaces then you get an error "Illegal character in fiel path" during the build.

Current work around is to move your solution to a different path without spaces in the fiel path.

**Comment by daveaglick** [comment]
This appears related to #81

**Comment by daveaglick** [comment]
Also #80

**Comment by daveaglick** [comment]
This should be resolved in the next release, 0.7.2
