### ISSUE TITLE
guideline for vscode integration?

### ISSUE THREAD

**Issue by Thaina** [daveaglick/Scripty#88]
I have interest in your amazing project. And I wish I could use it on vscode

But C# in vscode on macos seem like it not use msbuild

Are there a guideline to correctly use your system on it?

**Comment by daveaglick** [comment]
VS Code doesn't have support for the same extension concepts that the full Visual Studio has. Specifically, the Scripty custom tool is a type of extension called a Single File Generator which doesn't exist in VS Code. It's possible that in the future a VS Code specific extension could be written to trigger Scripty in the same way Visual Studio Single File Generators work, but there's nothing like that today.

If you add Scripty as an [MSBuild task](https://github.com/daveaglick/Scripty#scriptymsbuild) that should work at build-time to trigger code generation regardless of if you build your app through Visual Studio or Visual Studio Code. You can also use the Scripty exe application to trigger code generation whenever you want, though the mechanism that calls the exe is up to you.
