### ISSUE TITLE
System.IO.FileSystem binding failure in VS 2015

### ISSUE THREAD

**Issue by StarkeContrast** [daveaglick/Scripty#89]
Built from source (branch: develop) this afternoon, and was able to install the VSIX against 2017 Pro (YAY!)

However, in a test project, I am unable to set the Custom Tool property on the script file and get the following error:

![image](https://cloud.githubusercontent.com/assets/6453941/24817044/032a94c2-1ba9-11e7-88ea-543de096a059.png)

**Comment by daveaglick** [comment]
Is this by chance a .NET Core project?

**Comment by StarkeContrast** [comment]
Additional data:

2015 Pro, the Custom Tool property is accepted, but a right click => Run Custom Tool yields:
![image](https://cloud.githubusercontent.com/assets/6453941/24817402/5e79ef7a-1baa-11e7-90fd-8354e882070e.png)

2017, yes, the test project is Core.
2015, no, the test project is Framework 4.6.1

Did I jump the gun assuming that this release meant Core support was available?

**Comment by MichaelFStarke** [comment]
2017, yes, the test project is Core.
2015, no, the test project is Framework 4.6.1

**Comment by MichaelFStarke** [comment]
Did I jump the gun assuming Core support was in this release?

:D

**Comment by daveaglick** [comment]
In the 2017 case you're probably hitting this: https://github.com/daveaglick/Scripty/issues/49#issuecomment-244487701

Core is supported, but only when using the Scripty MSBuild task (available via NuGet) or running scripty.exe as part of a build pipeline. Single File Generators (which is the extension mechanism for custom tools in Visual Studio) aren't supported by .NET Core projects and it's not clear if they ever will be.

Not sure about the error you're seeing in 2015 - any way to get more info?

**Comment by StarkeContrast** [comment]
From a fresh VS2015 load and solution open, right click => Run Custom Tool yields the following in the Error pane:

```
Error		Custom tool error: System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromAssemblyInternal(Assembly assembly, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.CreateReferenceFromAssembly(Assembly assembly)
   at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.<>c__DisplayClass4_0`2.<SelectChecked>b__0(T item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.AddRangeChecked[T](ArrayBuilder`1 builder, IEnumerable`1 items, String parameterName)
   at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.ToImmutableArrayChecked[T](IEnumerable`1 items, String parameterName)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.WithReferences(IEnumerable`1 references)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.WithReferences(IEnumerable`1 references)
   at Scripty.Core.ScriptEngine.<Evaluate>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Scripty.ScriptyGenerator.GenerateCode(String inputFileContent) in Z:\!Code\Scripty\src\Scripty.CustomTool\ScriptyGenerator.cs:line 59
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromAssemblyInternal(Assembly assembly, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.CreateReferenceFromAssembly(Assembly assembly)
   at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.<>c__DisplayClass4_0`2.<SelectChecked>b__0(T item)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.AddRangeChecked[T](ArrayBuilder`1 builder, IEnumerable`1 items, String parameterName)
   at Microsoft.CodeAnalysis.Scripting.ParameterValidationHelpers.ToImmutableArrayChecked[T](IEnumerable`1 items, String parameterName)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.WithReferences(IEnumerable`1 references)
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.WithReferences(IEnumerable`1 references)
   at Scripty.Core.ScriptEngine.<Evaluate>d__6.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
<---	ConsoleApplication2	C:\Users\MichaelStarke\documents\visual studio 2015\Projects\ConsoleApplication2\Class1.csx	1
```

**Comment by daveaglick** [comment]
Okay, thanks - that's probably the same as https://github.com/daveaglick/Scripty/issues/84#issuecomment-292555532

Since that comment was added to an existing issue (since closed) I'll use this issue to track the "System.IO.FileSystem" binding failure in 2015. Working on it right now as a matter of fact :smile:

**Comment by StarkeContrast** [comment]
As an aside, the generation seems to be working in the MSBuild pipeline for the Core project in 2017!
(at least in a test solution)

👍

**Comment by daveaglick** [comment]
I'll take a win where I can get it!

The recent shifts in .NET library structuring have not been kind to this project. Been spending a lot of time finding and fixing binding issues like this one. Hopefully we're getting to the tail end of that now that .NET Standard 2.0 is around the corner.

**Comment by daveaglick** [comment]
I think the root of this particular binding problem is that even though the redirect is in the app.config of the VSIX, that's not processed by the VS extension engine. Found a little more information here: http://stackoverflow.com/questions/31246064/how-to-do-dll-bindingredirect-in-a-vsix-extension

@MichaelFStarke I've got a job for you - since you're able to build and run the vsix on VS 2015 (I actually don't have a copy readily available anymore), can you check out the latest commit and see where we're at? I'm hoping to have at least gotten past that first binding error and I'm curious to see if it works now or if we get follow-up binding errors. Thanks!

**Comment by StarkeContrast** [comment]
I'm out at dinner, but I would be happy to try that when I get home.

---Michael

On Apr 7, 2017 17:02, "Dave Glick" <notifications@github.com> wrote:

I think the root of this particular binding problem is that even though the
redirect is in the app.config of the VSIX, that's not processed by the VS
extension engine. Found a little more information here:
http://stackoverflow.com/questions/31246064/how-to-do-
dll-bindingredirect-in-a-vsix-extension

@MichaelFStarke <https://github.com/MichaelFStarke> I've got a job for you
- since you're able to build and run the vsix on VS 2015 (I actually don't
have a copy readily available anymore), can you check out the latest commit
and see where we're at? I'm hoping to have at least gotten past that first
binding error and I'm curious to see if it works now or if we get follow-up
binding errors. Thanks!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/daveaglick/Scripty/issues/89#issuecomment-292650993>,
or mute the thread

**Comment by daveaglick** [comment]
Thanks! And no rush at all - I probably won't get a chance to follow-up for a couple days given the weekend.

**Comment by dahauns** [comment]
This is indeed the same problem referenced here: https://github.com/daveaglick/Scripty/issues/84#issuecomment-292555532

I built the VSIX in VS2015 and indeed the first binding error was resolved - leading to subsequent binding errors, of course. :)

But I actually managed to get Scripty to run as a custom tool again - by including all redirects from the app.config in the AssemblyInfo.cs except the Build/CodeAnalysis ones. (I did have to add them as a Reference to the project as well though.)

```
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Microsoft.VisualStudio.Shell;

[assembly: AssemblyTitle("Scripty.CustomTool")]
[assembly: AssemblyDescription("")]
[assembly: Guid("dd26cc89-e1e8-4a94-8e8c-ad5215616c6c")]
[assembly: ComVisible(true)]

[assembly: ProvideBindingRedirection(AssemblyName = "System.IO.FileSystem", PublicKeyToken = "b03f5f7f11d50a3a",
    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "4.0.2.0", NewVersion = "4.0.2.0")]

[assembly: ProvideBindingRedirection(AssemblyName = "System.IO.FileSystem.Primitives", PublicKeyToken = "b03f5f7f11d50a3a",
    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "4.0.2.0", NewVersion = "4.0.2.0")]

[assembly: ProvideBindingRedirection(AssemblyName = "System.Collections.Immutable", PublicKeyToken = "b03f5f7f11d50a3a",
    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "1.2.1.0", NewVersion = "1.2.1.0")]

[assembly: ProvideBindingRedirection(AssemblyName = "System.Diagnostics.StackTrace", PublicKeyToken = "b03f5f7f11d50a3a",
    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "4.0.3.0", NewVersion = "4.0.3.0")]

[assembly: ProvideBindingRedirection(AssemblyName = "System.Security.Cryptography.Primitives", PublicKeyToken = "b03f5f7f11d50a3a",
    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "4.0.1.0", NewVersion = "4.0.1.0")]

[assembly: ProvideBindingRedirection(AssemblyName = "System.Xml.XPath.XDocument", PublicKeyToken = "b03f5f7f11d50a3a",
    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "4.0.2.0", NewVersion = "4.0.2.0")]

[assembly: ProvideBindingRedirection(AssemblyName = "System.Diagnostics.FileVersionInfo", PublicKeyToken = "b03f5f7f11d50a3a",
    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "4.0.1.0", NewVersion = "4.0.1.0")]

[assembly: ProvideBindingRedirection(AssemblyName = "System.Composition.AttributedModel", PublicKeyToken = "b03f5f7f11d50a3a",
    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "1.0.30.0", NewVersion = "1.0.30.0")]

[assembly: ProvideBindingRedirection(AssemblyName = "System.Composition.Runtime", PublicKeyToken = "b03f5f7f11d50a3a",
    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "1.0.30.0", NewVersion = "1.0.30.0")]

[assembly: ProvideBindingRedirection(AssemblyName = "System.Composition.TypedParts", PublicKeyToken = "b03f5f7f11d50a3a",
    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "1.0.30.0", NewVersion = "1.0.30.0")]

[assembly: ProvideBindingRedirection(AssemblyName = "System.Composition.Hosting", PublicKeyToken = "b03f5f7f11d50a3a",
    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "1.0.30.0", NewVersion = "1.0.30.0")]


[assembly: ProvideBindingRedirection(AssemblyName = "System.Threading.Thread", PublicKeyToken = "b03f5f7f11d50a3a",
    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "4.0.1.0", NewVersion = "4.0.1.0")]

[assembly: ProvideBindingRedirection(AssemblyName = "System.Reflection.Metadata", PublicKeyToken = "b03f5f7f11d50a3a",
    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "1.4.1.0", NewVersion = "1.4.1.0")]

[assembly: ProvideBindingRedirection(AssemblyName = "System.Xml.ReaderWriter", PublicKeyToken = "b03f5f7f11d50a3a",
    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "4.1.0.0", NewVersion = "4.1.0.0")]



//[assembly: ProvideBindingRedirection(AssemblyName = "Microsoft.Build", PublicKeyToken = "b03f5f7f11d50a3a",
//    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "15.1.0.0", NewVersion = "15.1.0.0")]

//[assembly: ProvideBindingRedirection(AssemblyName = "Microsoft.Build.Framework", PublicKeyToken = "b03f5f7f11d50a3a",
//    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "15.1.0.0", NewVersion = "15.1.0.0")]



//[assembly: ProvideBindingRedirection(AssemblyName = "Microsoft.CodeAnalysis", PublicKeyToken = "31bf3856ad364e35",
//    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "2.0.0.0", NewVersion = "2.0.0.0")]

//[assembly: ProvideBindingRedirection(AssemblyName = "Microsoft.CodeAnalysis.CSharp", PublicKeyToken = "31bf3856ad364e35",
//    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "2.0.0.0", NewVersion = "2.0.0.0")]


[assembly: ProvideBindingRedirection(AssemblyName = "System.IO.Compression", PublicKeyToken = "b77a5c561934e089",
    OldVersionLowerBound = "0.0.0.0", OldVersionUpperBound = "4.1.2.0", NewVersion = "4.1.2.0")]
```

**Comment by StarkeContrast** [comment]
@dahauns Thanks for sussing that out.  I got distracted, toddlers and playgrounds...  who knew?

**Comment by daveaglick** [comment]
@dahauns Thank you *so* much for running that to ground! I've added all the redirect attributes and am just about ready to publish a new version. This'll be a pain to update when new redirects are needed, but at least it works.

One question:
> I did have to add them as a Reference to the project as well though

Right now those assemblies are being included as VSIX items by copying from the Scripty.Core build:

```
  <ItemGroup>
    <VSIXSourceItem Include="..\Scripty.Core\bin\$(Configuration)\*.dll" Exclude="..\Scripty.Core\bin\$(Configuration)\Scripty.Core.dll" />
  </ItemGroup>
```

Did you also need to add the Microsoft.Build.* and Microsoft.CodeAnalysis.* as direct references in the project in addition to bringing them in as VSIX items?

**Comment by dahauns** [comment]
The problem wasn't having to include the assemblies as VSIX items, but that the build of Scripty.CustomTool would fail without direct references in that project.

Seems that redirects in AssemblyInfo.cs can't reference libraries only included through dependent projects (or maybe I'm just missing a line somewhere?)

And no, the Microsoft packages weren't affected by this.  
But: with the redirects, VS 2015 wouldn't open projects anymore when the 2017 (i.e. 15.x.x.x) Build Tools aren't installed on the system, no matter whether they are included in the VSIX.

**Comment by daveaglick** [comment]
> But: with the redirects, VS 2015 wouldn't open projects anymore when the 2017 (i.e. 15.x.x.x) Build Tools aren't installed on the system, no matter whether they are included in the VSIX.

Yeah, I think that's a function of updating to Roslyn 2.0 - it uses the VS 2017 MSBuild libraries via MEF. If those build tools aren't on the system it'll fail. Just tackled this with another project that uses Roslyn `MSBuildWorkspace`. My AppVeyor builds were failing because I hadn't toggled them from the VS 2015 image to the VS 2017 one.

**Comment by daveaglick** [comment]
I think it's an acceptable trade. The alternative is staying on the old version of Roslyn, but then Scripty would fail for any sort of recent project type. It's a bit of a catch-22, but I'd rather support more modern projects out of the box and require users with older IDEs to install the build tools then not have support for the new project types.

**Comment by daveaglick** [comment]
Just release 0.7.3, hopefully this is resolved now.

**Comment by daveaglick** [comment]
Going to close this issue - please open a new one if it looks like this remains unresolved or you hit the problem again.
