### ISSUE TITLE
Broken under Xamarin Studio / Mono

### ISSUE THREAD

**Issue by petersondrew** [daveaglick/Scripty#92]
Previously, Scripty.MSBuild 0.5.0 worked just fine under Xamarin Studio / Mono. However with the introduction of https://github.com/daveaglick/Scripty/commit/7a4fe880494e4382cf48e9d9aedf739fea2c0f80 that is no longer the case. It seems the `_host` private member is not available on the build engine. I also checked if `host` was available, even though the MSBuild version is 14.0 and it is not available either.

What was the use case for bringing all that stuff in? Is there a less brittle solution? I'm anxious to help fix this if I can.

**Comment by daveaglick** [comment]
Use case was to allow Scripty to access the MSBuild properties of it's host project. I.e., if you wanted to write a script that changed output based on the type of build, or the output folder, or any optimizations, etc.

What exact error are you seeing? As far as I can tell, the entire host access is enclosed in a try/catch (https://github.com/daveaglick/Scripty/commit/7a4fe880494e4382cf48e9d9aedf739fea2c0f80#diff-32923a3808e56fea176fe3bb2136909aR221). Is the problem potentially that we're logging an error if it throws (which I think causes MSBuild to fail the task in some cases)? If logging the error is what's causing the issue, I'm totally find turning that into a warning instead, or even just a message.

Even better would be not to rely on exception handling at all. If we could invoke in such a way that didn't throw, like finding the MemberInfo before invoking it and bailing if it can't be found, that'd be great.

**Comment by petersondrew** [comment]
I think you're correct, logging it as an error is the reason the build fails. I will attempt to rewrite it so that it doesn't throw exceptions, and if for some reason we do simply log it as a warning.

**Comment by daveaglick** [comment]
I went ahead and changed the log error to a warning so it shouldn't fail your builds anymore. Change is going out with the 0.7.4 version soon.
