### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by thenameless314159** [daveaglick/Scripty#93]
Hi, i have an issue when i add ScriptyGenerator as a custom tool i have the following error : 

```
Erreur		Erreur de l'outil personnalisé : System.IO.FileNotFoundException: Impossible de charger le fichier ou l'assembly 'Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ou une de ses dépendances. The system cannot find the file specified.
Nom de fichier : 'Microsoft.VisualStudio.Shell.15.0, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   à Scripty.BaseCodeGeneratorWithSite.GetService(Type serviceType)
   à Scripty.BaseCodeGeneratorWithSite.GetProjectItem() dans E:\Code\Scripty\src\Scripty.CustomTool\BaseCodeGeneratorWithSite.cs:ligne 158
   à Scripty.ScriptyGenerator.GenerateCode(String inputFileContent) dans E:\Code\Scripty\src\Scripty.CustomTool\ScriptyGenerator.cs:ligne 0
```

I'm on VS2015 with .NET framework project, I use the VS extensions and this happens on every .csx i made with ScriptyGenerator as a custom tool.

The test script doesn't generate itself when i use the custom tool it throw an error just like this : 

![issue](http://i.imgur.com/W5M9v1t.png)

I've been able to generate some class but it happens magically on some try .__.

**Comment by daveaglick** [comment]
Looks like the VSIX is relying on some references from the VS 2017 SDK. I'm going to try tweaking it a bit to get this resolved in the next release.

**Comment by daveaglick** [comment]
Okay, made the changes and tested them out. I'm going to call this resolved with the next release. If you continue to have problems after 0.7.4 is out please open a new issue.

**Comment by thenameless314159** [comment]
I've updated vs to 2017 version therefore it should be fine now, ty ! Great work anyway n_n
