### ISSUE TITLE
JSON.NET - non-dev package reference

### ISSUE THREAD

**Issue by aarondandy** [daveaglick/Scripty#96]
I added a recent Scripty.MSBuild 0.7.3 to a project and it also ended up taking a non-dev dependency on JSON.NET `<package id="Newtonsoft.Json" version="10.0.2" targetFramework="net461" />` . I forget how all this works but maybe it needs to be marked as `developmentDependency="true"` in the nuspec somehow?

**Comment by daveaglick** [comment]
Maybe...though on second I'm actually not sure it should be a development dependency. The MSBuild task does use Json.NET to encode and pass date to the Scripty CLI application so it does need the library locally. It's not a good look for that to get pulled into the whole project though, especially if it results in conflicts.

I'm thinking there's a couple options here:
- ILMerge Json.NET (bleh)
- Distribute the Json.NET libraries in the package without taking a dependency and then make sure the task can find them
- Use a different source-only JSON encoder

**Comment by daveaglick** [comment]
I've confirmed that marking Json.NET as a `developmentDependency` removes the package dependency but continues to pack the assembly directly. This change will go out with the next release.
